spring.application.name=OptiBankBuddy

server.port=4545

spring.datasource.url=jdbc:mysql://localhost:3306/optibankbuddy
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shadow78548@gmail.com
spring.mail.password=vvly pfnl qrlu wtuz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.file.name=logs/optibankbuddy.log
logging.level.root=INFO

